### ISSUE TITLE
no HDMI audio - GA-Z77X-UD5H

### ISSUE THREAD

**Issue by n3m3basat** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#10]
Hi,

First of all, thnx to theracermaster to have this patch four our MB's. :D 
I run the patch, but my HDMI audio doesn't work. True that my Bios is on factory version, so I didn't update BIOS. 
I'm a newbie using Clover and patching stuff. Any help?
Thnx

My setup:
GA-Z77X-UD5H
i7 3770K
NVidia GT 660 Ti
El Capitan

**Comment by theracermaster** [comment]
Can you please post IOReg dump with [IORegistryExplorer v2.1](https://github.com/toleda/audio_ALCInjection/blob/master/IORegistryExplorer_v2.1.zip) (File > Save As)?

**Comment by n3m3basat** [comment]
Hi, I was solve the problem with this one: https://www.google.si/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CB0QFjAAahUKEwiizYWy17rIAhUo1XIKHadkB0w&url=https%3A%2F%2Fraw.githubusercontent.com%2Ftoleda%2Faudio_ALCInjection%2Fmaster%2F%255BGuide%255D-Add_HDEF-Clover.pdf&usg=AFQjCNHV9_TkXLw-TS1iBZfLzNKfzDlrsw&sig2=58s-phhdgevHHRlWaH4WwA&bvm=bv.104819420,d.bGQ

**Comment by theracermaster** [comment]
What modifications did you make to config.plist? I would like to see so I can add them to the main script.

**Comment by n3m3basat** [comment]
I make modifications like its write on upper guide, so just a few thing in Clover:
1.AddDTGP_0001/YES
2.FixHDA_8000/YES
3.Debug/YES
4.Devices/Audio/Inject/1

**Comment by n3m3basat** [comment]
https://drive.google.com/folderview?id=0B8QWhIu2gUlCV2pld1hteDUzZWM&usp=sharing

IO Reg and config.plist

**Comment by theracermaster** [comment]
Hmm...second instance of the SSDT not working properly...can you press F4 at the Clover boot screen? This will dump your default ACPI tables to EFI/Clover/ACPI/origin. Please post them here.

**Comment by n3m3basat** [comment]
here is the dumplog.txt

https://drive.google.com/open?id=0B8QWhIu2gUlCLUJXZVQ1RVZRMVE

**Comment by theracermaster** [comment]
Can you post the DSDT.aml in the EFI/Clover/ACPI/origin folder?

**Comment by n3m3basat** [comment]
folder updated. I upload every file from folder. :)

**Comment by theracermaster** [comment]
SSDT breakage was caused by IGPU not being enabled in UEFI. Enabling it will fix the issues automatically, so there is nothing for me to fix.
