### ISSUE TITLE
error running ./GA-Z77X.sh --inject-hda

### ISSUE THREAD

**Issue by ch0w7** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#11]
/System/Library/Extensions/AppleHDA.kext failed to load - (libkern/kext) different version/uuid already loaded; check the system/kernel logs for errors or try kextutil(8).
sudo: /Users/Ch0w/Downloads/Gigabyte-GA-Z77X-DSDT-Patch-master/externals/hdaInjector.sh/hdaInjector.sh: command not found
Merge: Error Reading File: /tmp/ktp.plist

What do I do? I can't get audio working. I worked before I ran this script to fix my boot timeout.

**Comment by theracermaster** [comment]
You need to clone the repo with the `--recursive` flag so all of the external dependencies (such as hdaInjector.sh) are downloaded as well.

**Comment by ch0w7** [comment]
That worked, however I ran all of the commands and overwrote everything including clover and I still get no audio devices showing up.

**Comment by theracermaster** [comment]
Can you please post an IOReg dump using [IORegistryExplorer v2.1](https://github.com/toleda/audio_ALCInjection/blob/master/IORegistryExplorer_v2.1.zip) (File > Save As)?

**Comment by ch0w7** [comment]
https://mega.nz/#!aE9RDTYK!LegNZG2ToKxTKWKDWhYBZndNmeG3MBVM9_U2oJo4WJg

**Comment by theracermaster** [comment]
Do you have FireWire disabled in the UEFI?

**Comment by ch0w7** [comment]
I believe I disable FireWire in the bios because I do not use it.

**Comment by theracermaster** [comment]
Try [this](https://transfer.sh/dL0Q6/ssdt-tiny.aml.zip) SSDT. Place it in EFI/Clover/ACPI/patched (replacing the existing SSDT).

**Comment by ch0w7** [comment]
still no output devices

**Comment by theracermaster** [comment]
Can you please post another IOReg?

**Comment by ch0w7** [comment]
https://mega.nz/#!rEkD3Dpa!a-D5mK5LftVccTSX4PLrBl18byZYig2f6wgUVfWDUSQ

**Comment by theracermaster** [comment]
Looks like you have the IGPU disabled. It's recommended to enable it in the wiki to get all features (such as AirPlay Mirroring) working, but if you don't want to, try [this SSDT](https://transfer.sh/ZqGc6/ssdt-tiny.aml.zip) which has all IGPU injection removed.

**Comment by ch0w7** [comment]
Where is the wiki? Everything seems to work fine with the machine except for the audio

**Comment by theracermaster** [comment]
The SSDT is what handles the audio layout ID injection. The original one from the repo wasn't loading on your system was most likely due to your missing FRWR device (since you didn't have FireWire enabled).

**Comment by ch0w7** [comment]
So I should turn everything back on in the bios and rerun the script?

**Comment by theracermaster** [comment]
Yes, you could do that, or you could use the modified one I linked in this thread ("Looks like you have the IGPU disabled...") which doesn't have FireWire device injection.

**Comment by ch0w7** [comment]
I turned on firewire and reran the script and got an error. Here is the terminal log:

Gigabyte GA-Z77X.sh Post-Install Script v1.8.2 by theracermaster
Updates & Info: https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch
--------------------------------------------------------------------------------
Detected motherboard: Gigabyte GA-Z77X-UP5-TH
Script arguments: ./GA-Z77X.sh --install-ssdt: Compiling Custom SSDT
--------------------------------------------------------------------------------
EFI system partition (disk2s1) mounted at /Volumes/EFI.
Downloading SSDT-GA-Z77X-UP5-TH.dsl:
######################################################################## 100.0%
Compiling SSDT-GA-Z77X-UP5-TH.dsl:

Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20150818-64
Copyright (c) 2000 - 2015 Intel Corporation

ASL Input:     /tmp/SSDT-GA-Z77X-UP5-TH.dsl - 519 lines, 14658 bytes, 281 keywords
AML Output:    /tmp/SSDT-GA-Z77X-UP5-TH.aml - 2891 bytes, 133 named objects, 148 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 22 Optimizations

SSDT compilation complete. Exiting...
Hackintosh:Gigabyte-GA-Z77X-DSDT-Patch Ch0w$ ./GA-Z77x.sh --inject-hda
This part of the script needs to be run as root.
Password:

/System/Library/Extensions/AppleHDA.kext failed to load - (libkern/kext) different version/uuid already loaded; check the system/kernel logs for errors or try kextutil(8).
sudo: /Users/Ch0w/Gigabyte-GA-Z77X-DSDT-Patch/externals/hdaInjector.sh/hdaInjector.sh: command not found
Merge: Error Reading File: /tmp/ktp.plist
Hackintosh:Gigabyte-GA-Z77X-DSDT-Patch Ch0w$

**Comment by theracermaster** [comment]
You didn't clone the repo with the `--recursive` argument, which downloads the external repos.

**Comment by ch0w7** [comment]
I did. the error is " /System/Library/Extensions/AppleHDA.kext failed to load - (libkern/kext) different version/uuid already loaded; check the system/kernel logs for errors or try kextutil(8).

do I need an original AppleHDA.kext to replace what is currently there?

**Comment by ch0w7** [comment]
Ok. I reinstalled the applehda.kext that I got from the el capitan installer.Rebooted and installed your script with no errors. Rebooted and still no audio devices show. Here is the IO file: https://mega.nz/#!nNNAFIBI!GP3At2sKl6EKddp8VVuQiqL_9mPPFmAEvOGhtdqPaY4

**Comment by theracermaster** [comment]
That error can be safely ignored, I should probably output it to /dev/null so the user never sees it. This is an SSDT issue, will fix this ASAP.

**Comment by theracermaster** [comment]
SSDT issue is fixed with latest version, please try & report back; you don't have to redo everything, you can just compile SSDT-GA-Z77X-UP5-TH.dsl in the ACPI table repo and replace SSDT-HACK.aml in EFI/Clover/ACPI/patched with it.

**Comment by ch0w7** [comment]
I am not sure how to do that so I will just rerun everything. I will try to get to it in an hour.

**Comment by ch0w7** [comment]
well. I ran all of the scrips again and still no output devices. I am at a loss.

**Comment by ch0w7** [comment]
Ok. I fixed it!!
Here is what I did:
mounted EFI, ran clover configurator and put a 1 for audio. saved and rebooted.
then I ran 
git clone --recursive https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch.git
then 
./GA-Z77X.sh --compile-ssdt
then 
./GA-Z77x.sh --inject-hda

I then took the SSDT-HACK.aml from the Gigabyte-GA-Z77X-DSDT-Patch folder and replaced it in the EFI partition.

Thanks for all the help. Do you have a place to donate?

**Comment by theracermaster** [comment]
Thanks for the feedback, nice to hear you got this working.
