### ISSUE TITLE
Kernel Panic on Boot with USB Install Stick

### ISSUE THREAD

**Issue by mickelsn** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#12]
Greetings...I'm having a problem getting a USB stick prepared with your EFI method to boot. I get through the verbose boot script and see creation of RAM disks, a number of Mission Bluetooth Controller Transport errors, eventual mounting of my installation target SSD, but the boot eventually Kernel Panics out and restarts the boot loop.

This happens on a GA-Z77X-UP5-TH motherboard with 32GB RAM, 3770K processor, and only one SSD drive connected via SATA ports. The KP happens whether I'm trying to boot from USB in a USB3 case port connected to MB header, USB3 port from the on the back of the board, or a USB2 port on the back of the board.

This configuration boots just fine with the TonyMac UniBeast installation method.

Any ideas? Anything I can find from the USB stick (boot logs) and try to post to help diagnosis?

**Comment by theracermaster** [comment]
What version of OS X are you trying to install? What GPU are you using? Actually... this is probably my fault, there was a bug that I recently fixed, but I probably forgot to update the SSDT in the installer files... let me fix this.

**Comment by mickelsn** [comment]
I'm trying to install Mac OS X 10.11 (El Capitan). This happens with integrated graphics - my GeForce 650Ti card is pulled from the PCIExpress slot when I install. BIOS set to IGFX for the install per your recommendation.

**Comment by theracermaster** [comment]
Fixed with latest commit in [the Gigabyte GA-Z77X OS X Install repo](https://github.com/theracermaster/Gigabyte-GA-Z77X-OS-X-Install/commit/a840e099fcff6d7cc1ee635a42b035133b6c6713).

**Comment by mickelsn** [comment]
Just to confirm - the fix to v1.8.4 of your package worked just fine for me on my GA-Z77X-UP5 TH motherboard to boot and install El Capitan. Thank you!!

**Comment by theracermaster** [comment]
Thanks for the feedback.
