### ISSUE TITLE
Error in EFI Volume Mount Script in v1.8.4

### ISSUE THREAD

**Issue by mickelsn** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#14]
As noted in a thread on Issue #13 , the `_mountEFI` function in the GA-Z77X.sh script would error out for me as follows:

```
./GA-Z77X.sh: line 130: [: too many arguments
```

I was able to fix this error by pulling the Core Storage test `grep` into a variable and then test against the variable in the `if` statement. My fix inserts the following code as a new line above existing line 130 in your script:

```
		csVolumeTest=$(diskutil info "$osVolume" | grep "Core Storage")
```

The existing line 130 (now line 131 after inserting the above) is then edited to read:

```
		if [ ! -z "$csVolumeTest" ]; then ## CS volume detected
```

[Shout out to StackExchange](http://stackoverflow.com/questions/13781216/bash-meaning-of-too-many-arguments-error-from-if-square-brackets) for helping me understand what was going on here.

**Comment by theracermaster** [comment]
Thanks. Will update this soon.

**Comment by theracermaster** [comment]
Should be fixed with the latest commit. Thanks for the suggestion again.
