### ISSUE TITLE
AirPlay Mirroring Not Enabled with PCIe Primary, Intel Graphics Enabled

### ISSUE THREAD

**Issue by mickelsn** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#15]
First, let me open up by saying THANKS for putting these scripts together -- this is the closest I've ever been to fully utilizing the capabilities of my Mackintosh after a couple years. I'm particularly interested in getting Airplay video mirroring to work.

So -- I was thrilled to see the option for Airplay mirroring in my menu bar upon successfully installing El Capitan using your scripts. However, when I went back to my PCIe graphics card (GeForce GTX 650 Ti) being primary with Intel graphics Enabled in BIOS (not Auto), the option is no longer available to me. I've checked Display preferences, and the option to see the menu bar item for Airplay is still enabled.

Interestingly enough, System Information only shows me my GeForce graphics card data -- it DOES NOT  show me the Intel 4000 graphics from my 3770K processor.

Any ideas? I'd like to keep running my two displays from the GeForce graphics card and use the Intel Graphics for Airplay only. Let me know what data you need if you have the patience to troubleshoot.

**Comment by theracermaster** [comment]
Do you see the AirPlay icon in the menu bar, or is it missing? It shouldn't show up in System Information, this is intentional (real iMacs will hide the IGPU but still use it for QuickSync/AirPlay Mirroring).

**Comment by mickelsn** [comment]
AirPlay icon is missing when BIOS is set to PCIe graphics to init first. This happens with both monitors connected to the GeForce card, and also with one monitor connected to the GeForce card and another connected to the motherboard integrated graphics port (DVI). Interestingly enough, the monitor connected to IGPU port never got an image -- it was like the integrated graphics were completely disabled.

I was able to get the AirPlay icon back by changing BIOS settings for IGPU graphics to init first, and connecting one monitor (primary) to motherboard DVI port. Second monitor is connected to GeForce card. This gives me two entries in System Profiler - one Intel Graphics 4000, another for the GeForce GTX 650 Ti.

Motherboard is GZ-Z77X-UP5-TH.

**Comment by theracermaster** [comment]
Can you post an IOReg dump with PCIe GFX set to Init first with IGPU enabled?

**Comment by mickelsn** [comment]
Will do late tonight or sometime tomorrow US East Coast time. Thanks!

Neil Mickelson | neil@the-mickelsons.net

**Comment by mickelsn** [comment]
Here's a shot at the IOReg dump as requested. Let me know when you've downloaded. Thanks!

https://www.dropbox.com/s/xiedm0xxtvql357/Macintosh.ioreg.zip?dl=0

**Comment by theracermaster** [comment]
Thanks. Confirms what I was thinking, SSDT is breaking and not injecting proper IG platform ID (see other thread for more info).

**Comment by mickelsn** [comment]
Confirming fixed -- updated the SSDT from the online repo in Issue #16 , then successfully booted with both monitors running off of my PCIe graphics card and Airplay video mirroring available in menubar. I successfully sent video to one of my AppleTVs (Gen. 3 model) as a third monitor for the computer -- first time being able to do that on my Hackintosh!

This is really awesome - thanks much! Now to tune my Clover config.plist for graphics screen size, etc., during startup and I'm fully in business!
