### ISSUE TITLE
SUGGESTION: Fix Known SystemID (SmUUID) Issue for Gigabyte Boards in Generated config.plist

### ISSUE THREAD

**Issue by mickelsn** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#18]
A suggestion for your consideration...when your script writes the customized `config.plist` file for the detected motherboard, you may want to generate random UUIDs to include as a `SmUUID` key. This would help ensure a better shot of success in using iMessage long-term on the resultant Hackintosh.

**Comment by theracermaster** [comment]
The script actually used to do this in the past (a few versions ago), but I removed it. Can you elaborate on the Gigabyte system ID issue? At least on my board, the UUID definitely looks random (no repeating blocks of 0).

**Comment by mickelsn** [comment]
[Best explanation of the issue I know of is here](http://www.tonymacx86.com/general-help/110471-how-fix-imessage.html#TOP5). I can successfully log into iMessage with a `SmUUID` key generated by multiple runs of the `uuidgen` command in the terminal and then adding it to `config.plist` via Clover Configurator.

**Comment by theracermaster** [comment]
Re-enabled SmUUID injection with latest commit.
