### ISSUE TITLE
Sudden Random Crashing on Previously-Stable Hardware

### ISSUE THREAD

**Issue by mickelsn** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#19]
I think there something unstable in my BIOS and/or EFI configuration that is contributing to all kinds of random crashing under EXCEEDINGLY light loads after installing Mac OS X 10.11.1 with your scripts. I've got my BIOS configured via your recommendations - Power Management, etc., all set to fixed values (not Auto), etc. I do not overclock.

MB is GA-Z77X-UP5-TH with BIOS version F11. Processor is Intel 3770K. Only running SSD and optical drives at the moment. I have an [Apple WiFi / Bluetooth card in PCI carrier from OSXWiFi](http://www.osxwifi.com/apple-broadcom-bcm94360cd-802-11-a-b-g-n-ac-bluetooth-4-0-with-adapter-for-pc-hackintosh) which identifies my hardware fairly well.

One weird thing -- when my UPS is connected via USB, I'd sometimes get spurious errors when my loving screen appeared that my UPS was nearly out of power, and then the dialog goes away nearly instantaneously after the login screen appearing.

None of this ever happened for nearly three years running on this hardware with a lot more drives (HD and SSD) plugged in, etc. Machine would have uptime measured in months. That install was Yosemite running largely with TonyMac's approach to Clover installation.

[Crash dumps uploaded](https://www.dropbox.com/s/fri2nanwnredq9y/Archive.zip?dl=0) in case you can help analyze the problem. Greatly appreciate your help with all of this!

**Comment by theracermaster** [comment]
I can't say I've seen this before. All I see on Google about that panic is bad RAM; you might want to check with memtest86+ in another OS. If it doesn't pass, you may want to double check that you entered your UEFI settings properly (try setting to Optimized Defaults) and test again.

**Comment by mickelsn** [comment]
Running memtest now. Machine has been stable for a day or two under light load, but without UPS plugged in...will see if that seems to induce errors.

**Comment by mickelsn** [comment]
OK, did a three-hour exhaustive test of RAM with MemText86 v6, all tests, from a bootable CD. Only ran from one processor core on my 3770K, not across all 4 plus the HyperThread-enabled "phantom" processors. 100% clean - zero errors.

I've got the UPS plugged in again to see if that makes any difference in things...basically, I'm in a "watch and wait" mode to see if I start crashing randomly again. Hopefully not, and it was just some transient after applying the OS X 10.11.1 and other updates. I suspect it might have been, because I forgot to hide the "Thunderbolt Firmware Update 1.2" before running all available updates for the OS and iTunes.

Alternatively, it might have been BIOS setting problems -- somewhere in the midst of the crashes, I dropped into BIOS and noticed that some of the settings had reverted to "Auto" instead of enabled, so I went through the whole BIOS configuration process again. Maybe that did the trick as you noted above.

For now, I'm going to close my issue since I can't re-create it. Thanks for the suggestions -- and for all the hard work on this script to keep users of a couple-generation-old family of motherboards up to speed!

**Comment by mickelsn** [comment]
For what it's worth -- it seems I've pretty definitively traced the contributing factor to crashing to my UPS (APC model, fairly old). I suspect it's some kind of interaction with USB configuration in the SSDT or something, since I have had the exact same UPS plugged into this machine under my old Clover install (Yosemite) without any SSDT. Every now and then on restart, I get a brief alert error on the login screen that I need to shut down immediately because my UPS is out of battery - it goes away, I log in, and I crash hard soon thereafter.

But frankly, I don't have the time to try and chase it down or isolate any further.

Once I have time to shutdown my NAS, which is on a newer APC UPS, I'll see if that seems to make any difference.
