### ISSUE TITLE
Can't compile ssdt -  Gigabyte Z77X-UD5H (rev.1.1)

### ISSUE THREAD

**Issue by anonym323** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#2]
I have problems at this step : ./GA-Z77X.sh --compile-ssdt - on my Gigabyte Z77X-UD5H (rev.1.1). I always get the message: ERROR:  motherboard is unsupported by this script. Exiting... What can I do ? Please help

**Comment by theracermaster** [comment]
Please post complete output of the script. Make sure you are using the latest version, too.

**Comment by anonym323** [comment]
Complete Output? What do you mean ? I used the Version 1.7.1 of the script. I get this message when I type it in the terminal.

**Comment by theracermaster** [comment]
Please run the following command in Terminal and post the output here (make sure you are in the repo directory first):
```tools/bdmesg" | grep "Z77X" | cut -d '-' -f2 | sed 's/[[:space:]]//g'```

**Comment by theracermaster** [comment]
I have made changes to the script; `bdmesg` is no longer required. Instead, the script will get the motherboard information from the IODeviceTree, where Clover injects the motherboard name. Please try the latest version.

**Comment by anonym323** [comment]
Tried it without any luck. Still the Same error... :(

**Comment by theracermaster** [comment]
Please post an IOReg dump using [IORegistryExplorer v2.1](https://github.com/toleda/audio_ALCInjection/blob/master/IORegistryExplorer_v2.1.zip).

**Comment by anonym323** [comment]
http://www73.zippyshare.com/v/n2jFWJUr/file.html

**Comment by theracermaster** [comment]
I would recommend a clean install using Clover (please read the wiki). You are currently using Chameleon/Chimera to boot; the script is designed for booting after a clean install using Clover.
