### ISSUE TITLE
vt2021 not working once again

### ISSUE THREAD

**Issue by krymzy** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#20]
I did a clean install, this time was able to install with igfx primary and monitor in mobo.

this time i have an old audiophile (m-audio 2496 wich i got working in 10.9 with Envy24 drivers) sound card in one of my pci slots - guess thats why the patch isn't working?

no audio device detected at all in sound settings

other thing i noticed (last install i couldn't just get mic working but sound was fine) is that the patch has different i/o layouts, can you point me to the point in the dsdt wich points to the layout? (i think i found it in the DSDT-HACK but i killed my last OS X install trying the 3rd option)

Thanks again for your great work

ioreg- https://dl.dropboxusercontent.com/u/15461903/Kaur%E2%80%99s%20iMac.ioreg

**Comment by theracermaster** [comment]
Try re-running `GA-Z77X.sh --git-update` && `GA-Z77X.sh --inject-hda`. I recently updated hdaInjector.sh to try out a new version of the VT2021 patches, but it appears they aren't working.

**Comment by krymzy** [comment]
Yup, that fixed it

Got sound output(no input) again

After applying the patch and rebooting again first i got a random reboot (tested the sound, opened safari and it occured while writing back here)
After the reboot i couldn't start safari (safari quit unexpected while using the CoreDuetDaemonProtocol plug in)

after a reboot it works again 
100% clean install according to your wiki and no 3rd party apps etc yet
