### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by shawnxjeong** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#24]
Hello, 

I was going through your guide and finished the UEFI Config. After I exited to boot off USB drive, my keyboard stopped working.. and could neither go to boot options nor BIOS... 

Afterwards, it gets stuck on the Apple logo with the circle of death.. Please Help! 

FYI, I am pretty amateur.. wanted to upgrade to El Capt and found your guide.

**Comment by shawnxjeong** [comment]
I'm on 
Intel Core i7-3770K
GA-Z77X-UD5H
EVGA GeForce GTX 660 SUPERCLOCKED 2048MB
Apple Wired Keyboard

**Comment by shawnxjeong** [comment]
nevermind. it was an issue with the apple keyboard.... 

But I will be bound to run into more issues so.. stay tuned!! 

Thanks for the great guide btw.

**Comment by shawnxjeong** [comment]
Hello there.

When I shut down, the system restarts.. I know I read that in one of the posts but I cannot find it..

I am on
Intel Core i7-3770K Quad-Core Processor 3.5 GHz
GA-Z77X-UD5H
EVGA GeForce GTX 660 SUPERCLOCKED 2048MB

**Comment by D-an-W** [comment]
Do you have Wake on LAN disabled in the BIOS?

**Comment by shawnxjeong** [comment]
oh... well that was easy..lol solved it. Thanks!!

Additionally however, I have Bose Companion 5 getting sound via USB. I get a humming noise when there is no sound output.. anyone know why?

**Comment by theracermaster** [comment]
Using the Clover Shutdown DSDT fix enables shutdown without having to disable Wake on LAN in the BIOS. It will be included in the default config.plist for v1.9 (which I'm still working on). As for USB audio, I'm not sure. I've heard that 10.11 caused some issues with certain DACs.

**Comment by D-an-W** [comment]
That's good to know Alex, excited to try v1.9!

**Comment by shawnxjeong** [comment]
Hey.. I am stuck on the black screen with Apple Logo... and the loading bar won't pop up... anyone have any idea?? Please HELP!! I am doing this for a friend and would like to finish today. 

same specs as my computer listed above. 
Thanks!

**Comment by theracermaster** [comment]
Boot verbose and post a picture of the output.

**Comment by shawnxjeong** [comment]
Hello,

Any news on additional updates? 

Additionally, I have Bose Companion 5 connected via USB 3.0
Often times, when there is no sound coming through the speakers, it makes a buzzing sound.. but when any form of sound comes through, it stops it.. do you know why??

**Comment by theracermaster** [comment]
I've been working on an updated version, just need some more time to complete & test it. As for your audio issue, are you on 10.11.4? I think early versions of El Capitan broke USB sound for some people.

**Comment by shawnxjeong** [comment]
I set up the same system for my friend and it has been working perfectly fine, but when he turned on the computer today, he would see the Apple Logo and then it would turn into a slashed circle... any ideas as to why? Thank You!

**Comment by colin-marshall** [comment]
@shawnxjeong boot verbose so you can see what caused the panic.

**Comment by shawnxjeong** [comment]
@colin-marshall I actually don't know how to do that.. I don't know what the command prompt is.. Please Help!

**Comment by theracermaster** [comment]
@shawnxjeong Press space when selecting the entry at the Clover boot screen, and select Boot verbose.

**Comment by shawnxjeong** [comment]
Hi @theracermaster, I am getting the following error:

Error loading Kernal cache  (0x7)

It is having issues right from the beginning.. Please Advise.
