### ISSUE TITLE
iTunes Video Download Playback Scrambled

### ISSUE THREAD

**Issue by mickelsn** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#29]
Greetings...long-time user of the current stable version of your script...but just found a new issue.

I just downloaded some 1080p iTunes video files (TV), and found that video playback is scrambled (audio is fine). Upon a bit of investigating, the same thing happens with movie files downloaded from iTunes -- both for a 1080p file as well as an SD file. The files play back fine on an iPad and via my AppleTV; also, non-iTunes SD and HD video files in my library play fine.

Given these symptoms, I suspect something in the video stream isn't tracking that the content is protected. What do you need to know about my system to troubleshoot? I have a dual-monitor system, one connected with VGA and one with DVI. Both monitors have the problem.

Thanks in advance...Neil

**Comment by theracermaster** [comment]
This is a common issue with DRM-protected content on hackintoshes. I'm not sure of any real fix, but will look for one.

**Comment by theracermaster** [comment]
[Shiki](https://github.com/vit9696/Shiki) fixes this. This will be added to the latest update.

**Comment by mickelsn** [comment]
Excellent, thanks! Do you have an estimate of when that update will come out? Perhaps in time for/just after the macOS Sierra release?

Very much appreciate your hard work and maintenance of this!

**Comment by theracermaster** [comment]
Should (hopefully) be out within a few weeks/by the end of this month (most likely before macOS Sierra's release).
