### ISSUE TITLE
Microsoft Windows Installation

### ISSUE THREAD

**Issue by shawnxjeong** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#30]
Hi Alex,

Can you please help me by providing some instruction on how I can install Windows on the Clover system? That would help me greatly!

Thank you!

Best,

Shawn Jeong

**Comment by theracermaster** [comment]
Windows can be installed the same way it would be installed on any UEFI system.

**Comment by shawnxjeong** [comment]
I don't have to go through Clover? Would the newly installed Microsoft OS show on the Clover boot menu? If not, how would I be able to access Windows?

Sorry to bombard you with all these questions.. Assistance, as always, would be very grateful.!!

**Comment by theracermaster** [comment]
As long as you install Windows in UEFI mode, you will be able to boot it through Clover (select the Windows Boot Manager option). It should be automatically detected after installing it.
