### ISSUE TITLE
Sierra boot loop KP

### ISSUE THREAD

**Issue by osenvosem** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#33]
z77x-ud5h I7-3770K, gtx680

I've installed Sierra on my z77x-ud5h well working configuration and can't boot after first reboot, got infinite boot loop. I'm able to boot only with `nv_disable=1` boot option otherwise I'm getting KP right before the desktop is supposed to appear.

I also try to create a new configuration but system didn't boot with "Install" EFI, just showed system messages on the screen.

Any ideas?

**Comment by osenvosem** [comment]
The reason of the KP was this section:
```
			<dict>
				<key>Comment</key>
				<string>[10.10+] Fix Boot Graphics Glitch (credit: RehabMan)</string>
				<key>Find</key>
				<data>
				AQAAdRc=
				</data>
				<key>Name</key>
				<string>IOGraphicsFamily</string>
				<key>Replace</key>
				<data>
				AQAAdBc=
				</data>
			</dict>
```

Please, update the script (and a new BIOS, if there is one) for Sierra.

**Comment by theracermaster** [comment]
Hi,

Thanks for the feedback. I'm almost done with the updated version of the script and will be updating it shortly (within the next week).

**Comment by osenvosem** [comment]
@theracermaster glad to hear that.

**Comment by mickelsn** [comment]
Just out of curiosity, how is the development of the updated script coming along? I'm looking forward to the upgrade so I can do a macOS Sierra install. Thanks again!

**Comment by colin-marshall** [comment]
@theracermaster any updates? thanks for all your work.
