### ISSUE TITLE
Report some errors while install(Sierra branch).

### ISSUE THREAD

**Issue by heathkimdev** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#37]
I tried to install this by some ways below,
1.  on zsh shell just `./GA-Z77X.sh --install` as described. Result is `zsh: ./GA-Z77X.sh: bad interpreter: /usr/local/bin/bash: no such file or directory`
2.  changed to bash `./GA-Z77X.sh --install` same result, `bad interpreter`
3. back to zsh `zsh ./GA-Z77X.sh --install` this seems work but causes **`iasl`** related error.(`command not found: iasl`)

====

I solved this but I think it's little nasty way.
Also, I have no idea about why it solved, some better way.

In addition, this may produce errors in another environment.

====

I think It's much better than multibeast from tonymacosx86.
Hackintosh works almost fine but has some minor problems with ethernet and sleep functionality.

I've been trying to solve those problems hardly but no luck.

Finally, I found this repo and gave it a try with little concern because I have no experience with DSDT related things.

It was not easy because of strange errors.
Eventually, I solved it with a little extra effort by the little tricky way and everything works fine now.

I'm very happy with it! 
Thanks a lot.

**Comment by theracermaster** [comment]
Thanks for reporting this, e3f88ad409db69b1ddea69dbf5267a1b268e7b46 fixes it.
