### ISSUE TITLE
Z77X-UP5 TH-CF not detected correctly

### ISSUE THREAD

**Issue by vodkaflip** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#4]
The (excellent!) script doesn't detect the Z77X-UP5 TH-CF correctly - the awk {'print $4'} part only returns the part before the space (Z77X-UP5), so the case statement fails for this board.

**Comment by theracermaster** [comment]
Thanks for the report, will fix this in 1.8.0.

**Comment by theracermaster** [comment]
This should be fixed in 1.8.0, please try it and report back.

**Comment by vodkaflip** [comment]
Thanks - detection works properly!
