### ISSUE TITLE
SSDTs cause kernel panic when using an IGPU

### ISSUE THREAD

**Issue by theracermaster** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#6]
Currently, the SSDTs [in the ACPI table repo](https://github.com/theracermaster/DSDT) work fine when using a discrete GPU along with the integrated GPU. But when using the IGPU by itself, kernel panics related to IOPCIFamily & AppleIntelFramebufferCapri occur. I'm still trying to figure out the cause of this.

**Comment by theracermaster** [comment]
This has been fixed with [the latest changes to the SSDTs](https://github.com/theracermaster/DSDT/commit/9bc4d7edd70129838d2663c021006f6827e19087).

**Comment by theracermaster** [comment]
This commit didn't actually fix it. Reopening and investigating further.

**Comment by TristanN47** [comment]
Confirmed got IOPCIFamily, AppleACPIPlatform & AppleIntelFramebufferCapri when booting solely from IGPU or connected to IGPU with discreet installed. Z77x-D3H

Got around by connecting discreet GPU to display & now installing

**Comment by theracermaster** [comment]
Made some progress on this. Using [ACPIDebug by RehabMan](https://github.com/RehabMan/OS-X-ACPI-Debug), I was able to check the device ID values being stored in the IGPU (integrated graphics) & GFX0 (PCIe graphics) devices by adding some debug statements to the _DSM methods in these devices, and it appears that the GFX0 device ID never gets stored:

    kernel[0]: ACPIDebug: Version 0.1.3 starting
    kernel[0]: ACPIDebug: ACPIDebug: { "Value of PEG0.GFX0.VID0", 0xffff }
    kernel[0]: ACPIDebug: ACPIDebug: { "Value of PEG0.GFX0.DID0", 0xffff }
    kernel[0]: ACPIDebug: ACPIDebug: { "Value of IGPU.VID0", 0x8086 }
    kernel[0]: ACPIDebug: ACPIDebug: { "Value of IGPU.VID0", 0x0162 }

Currently the script depends on checking the device ID of the GFX0 device to determine is a PCIe GPU is present or not, but that doesn't seem to work (as stated above). Perhaps checking _STA of the GFX0 device would be a better idea.

**Comment by theracermaster** [comment]
Should actually be fixed now. It appears that the vendor ID detection of the GFX0 device (PCIe GPU) was failing due to the address (_ADR) being set to 0xFFFF. After adding a Clover binpatch to change this to 0, it works as expected.
