### ISSUE TITLE
everything in /externals seem to be broken

### ISSUE THREAD

**Issue by krymzy** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#7]
all the script show up as a folder (using --git update  gives an error on one of them aswell)

dsdt compilation does not leave a .aml file in /tmp, hda compilation gives a merge error

also i was unable to boot el captain installer using the steps provided in the wik(installer files, tried with both yosemite and osmosis)i.

GA-Z77X-D3H f18k (also tried with osmosis and yosemite), el captain, intel 3770k, ga-nvidia 650ti (altho was plugged but monitor in mobo/unplugged)

here is a regdump using a install wich does not detect intel hd 4000 using latest unibeast uefi(clover) el captain install (without vide card defaults to Mac mini server 6.2)

https://www.dropbox.com/sh/3hb1s8dluy72sm2/AADoxN2pG9_mA9LCAa0-GJJDa?dl=0

**Comment by theracermaster** [comment]
Hi, please try cloning the repo with the `--recursive` argument. This should properly download all of the externals. What specific issues did you have booting the El Capitan installer with the instructions in the wiki?

**Comment by krymzy** [comment]
i killed my captain install with voodohda :D will fix it soon try the --recursive + dl a  new el captain installer to play with 

i got a kernel panic on every boot booting without nvidia card (and unplugged but inserted to the mobo, intel hd was set as primary and enabled)

not sure if its possible to read anything out of these  - 
![img_20151004_084545](https://cloud.githubusercontent.com/assets/5962549/10268258/994d7366-6abb-11e5-9ad0-fec728de7940.jpg)
![img_20151004_084614](https://cloud.githubusercontent.com/assets/5962549/10268259/99534390-6abb-11e5-8b66-d64a6a933b14.jpg)
![img_20151004_084626](https://cloud.githubusercontent.com/assets/5962549/10268260/9955d452-6abb-11e5-9c23-07501e70ff5e.jpg)
![img_20151004_084515](https://cloud.githubusercontent.com/assets/5962549/10268261/99596432-6abb-11e5-878f-eb5ead73c08c.jpg)
![img_20151004_084530](https://cloud.githubusercontent.com/assets/5962549/10268262/995bc0e2-6abb-11e5-9340-134a4efb1e08.jpg)

**Comment by theracermaster** [comment]
Panics caused by IGPU is a known bug with the SSDT (see issue #6). I'm still working on figuring this out (working with RehabMan). For now, use your NVIDIA GPU as the primary GPU (keep the IGPU enabled in the BIOS, though).

**Comment by krymzy** [comment]
tried again today, this is my ioreg dump with clover by this script

https://dl.dropboxusercontent.com/u/15461903/Kaur%E2%80%99s%20iMac.ioreg

https://dl.dropboxusercontent.com/u/15461903/CLOVER.zip (what your script generated)

with unibeast clover i saw intel hd4000 and nvidia under system report, now i don't (both monitors in nvidia card)


also hdainjector gives ERROR: No audio codec found in IORegistry! Exiting...

**Comment by theracermaster** [comment]
HD 4000 won't show up if used with a discrete GPU, this is intentional behavior in the SSDT. Real iMacs do the same thing - the IGPU is present but uses a platform ID that has zero connectors, so it won't appear. If you want to drive displays with the IGPU while using a discrete GPU, this behavior can be changed.

You need AppleHDA to load first so the script can ID the codec:
     $ sudo kextload /System/Library/Extensions/AppleHDA.kext

**Comment by krymzy** [comment]
tried loading applehda, kextload seemed successful (terminal didn't say anything)

getting

ERROR: No audio codec found in IORegistry! Exiting...
Merge: Error Reading File: /tmp/ktp.plist

**Comment by krymzy** [comment]
did a clean install again, had to install with monitor in nvidia card.. peg is primary

loaded the applehda kext before launching the script

still same error on applehda no codec found

https://dl.dropboxusercontent.com/u/15461903/Kaur%E2%80%99s%20iMac.ioreg

**Comment by krymzy** [comment]
after latest updates the sound is now working too

yay awesome! Thank you!!!

only problem i can see sow is line in or mic not working (+ i need to enable trim for non apple ssd-s)

new ioreg- https://dl.dropboxusercontent.com/u/15461903/Kaur%E2%80%99s%20iMac1.ioreg

**Comment by theracermaster** [comment]
This is an issue with Mirone's patched AppleHDA. Unfortunately I'm not good at all with patching AppleHDA, so I have no idea how to fix it. You might want to post [here](http://www.insanelymac.com/forum/topic/298663-applehda-for-yosemite) and ask Mirone/InsanelyDeepak for help.
