### ISSUE TITLE
Sleep issue

### ISSUE THREAD

**Issue by 2mny** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#78]
## System Information

 - OS: macOS 10.12.6 & 13.0.0 (HFS+)
 - Script: GA-Z77X macOS Install v2.1.0
 - MB: GA-Z77X-UD5H, F16h BIOS
 - CPU: Intel Core i5-3570k
 - IGPU: Intel HD Graphics 4000
 - dGPU: NVIDIA GeForce GTX 1060 6GB
## Issue Type

 - [x] I'm encountering errors during/after the post-install script

## Issue Description

Whenever system is manually put to sleep, the display turns off, the system runs for around 10s (mem dump to /var/vm/sleepimage ?) then powers off. A couple of seconds after shutting down, the system powers back up to a black screen. Moving the mouse or pressing a key on the keyboard wakes the display up.
If the system goes into sleep due to inactivity, the system performs the above actions in a loop, powering down, turning back on, then powering down again. The mouse and keyboard can be used to wake the system and interrupt the loop.

>     giga-hack:~ mike$ pmset -g
>     System-wide power settings:
>     Currently in use:
>      standby              1
>      Sleep On Power Button 1
>      womp                 0
>      autorestart          0
>      hibernatefile        /var/vm/sleepimage
>      powernap             0
>      networkoversleep     0
>      disksleep            10
>      sleep                15 (sleep prevented by AddressBookSourceSync)
>      autopoweroffdelay    28800
>      hibernatemode        0
>      autopoweroff         0
>      ttyskeepawake        1
>      displaysleep         10
>      standbydelay         4200

I have removed all of the the FakeSMC sensor kexts and changed out the default FakeSMC for the 2017-06-07 build of https://bitbucket.org/RehabMan/os-x-fakesmc-kozlek to resolve the Nvidia Pascal kernel panic. Besides these kext changes, my setup is a default ./GA-Z77X.sh --install for my board.

**Comment by joshuaseltzer** [comment]
Check your BIOS settings - I remember having this exact issue happen a long time ago with this board when I had Mavericks installed.  I believe it had something to do with the EHCI Handoff (just follow the instructions in the Wiki).

**Comment by 2mny** [comment]
Traced issue to newly installed liquid cooler. No more sleep issues after unplugging the USB header on the cooler that is used for controlling performance settings and lighting from Windows app.

Diagnosed the problem by checking system logs:

> giga-hack:~ mike$ log show --predicate "eventMessage contains 'Wake reason'" -last 1h
> Skipping info and debug messages, pass --info and/or --debug to include.
> Filtering the log data using "eventMessage CONTAINS "Wake reason""
> Timestamp                       Thread     Type        Activity             PID    
> 2017-11-28 22:11:49.204186-0600 0x73       Default     0x0                  0      kernel: (AppleACPIPlatform) Wake reason: PEG1 EHC1
> 2017-11-28 22:11:49.204186-0600 0x73       Default     0x0                  0      kernel: (AppleACPIPlatform) Wake reason: PEG1 EHC1
> 2017-11-28 22:15:07.691451-0600 0x73       Default     0x0                  0      kernel: (AppleACPIPlatform) Wake reason: PEG1 EHC1
> 2017-11-28 22:15:07.691452-0600 0x73       Default     0x0                  0      kernel: (AppleACPIPlatform) Wake reason: PEG1 EHC1
> 2017-11-28 22:16:06.259276-0600 0x73       Default     0x0                  0      kernel: (AppleACPIPlatform) Wake reason: PEG1 EHC1
> 2017-11-28 22:16:06.259277-0600 0x73       Default     0x0                  0      kernel: (AppleACPIPlatform) Wake reason: PEG1 EHC1
> 2017-11-28 22:19:26.585025-0600 0x73       Default     0x0                  0      kernel: (AppleACPIPlatform) Wake reason: PEG1 XHC1
> 2017-11-28 22:19:26.585025-0600 0x73       Default     0x0                  0      kernel: (AppleACPIPlatform) Wake reason: PEG1 XHC1
>  \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> Log      - Default:          8, Info:                0, Debug:             0, Error:          0, Fault:          0
> Activity - Create:           0, Transition:          0, Actions:           0

PEG1 is video card and EHC1 is USB. No changes to video card since sleep worked last so issue was likely USB. Unplugged USB devices one-by-one, testing sleep each time until the issue stopped.
