### ISSUE TITLE
Close to bricked

### ISSUE THREAD

**Issue by n8binus** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#80]
## System Information

 - OS: macOS 10.12.6
 - Script: GA-Z77X macOS Install v2.0.x
 -CPU i7-3770k Ivy Bridge 	Pentium G Series (7 Series) 
Socket: LGA1155
Graphics Card (GPU) EVGA GeForce GTX580
Mobo: GA-Z77X-UP5TH (Realtek ALC898 Codec)
Sandisk Extreme 120GB SSD, Corsair 550D, Dual Asus VN248 monitors
GPU Driver Version: 10.14.20 355.10.05.15f03
CUDA Driver Version: 6.5.51  

## Issue Type

 - [ ] I'm trying to boot the macOS installer
 - [ ] I'm trying to boot my macOS install

 - [x] I'm encountering errors during/after the post-install script

 - [ ] Can you add support for my board?

## Issue Description

First time Github user.

I'm a longtime Multibeast user and I was running 10.12.3.  Suddenly, my front usb ports stopped working.  First, I tried updating to Sierra 10.12.6 and updating with Multibeast.  That didn't work, so I googled around and thought I'd try running your script because my mobo is GA-Z77X-UP5TH , and hoped it would be a shortcut to magic.

I had a lot of trouble because your system seems designed for someone starting from scratch.  I used Carbon Copy Cloner to make a backup, then read about how to "clone the repository with --recursive flag"  [after getting this error.](https://github.com/al3xtjames/Gigabyte-GA-Z77X-macOS-Install/issues/74)

I tried running the script with the "--update" argument, but that didn't work, so I did "--install".  Well, my system wouldn't boot, so I messed around with the bios according to your instructions, but that didn't help. Using Clover boot option "verbose" I determined that I was [getting this error](https://www.tonymacx86.com/threads/solved-error-allocating-0x-pages-at-0x-alloc-type-2.182907/). 

That thread has a hundred possible solutions and nothing definite.  I was able to get 1 of my 2 monitors to boot using the clover boot option "nv_disable=1 system"

From there, I tried using your "--update" argument, but that didn't help.  So then I  tried following this guide to "[Remove extra Clover BIOS boot entries](https://www.tonymacx86.com/threads/guide-remove-extra-clover-bios-boot-entries-prevent-further-problems.175274/)"  but that made things much worse.

Now, on top of everything, I was having the terrifying "boot0 Error" without ever reaching the clover screen.  I tried following [this guide to fix it,](https://www.tonymacx86.com/threads/boot0-error-the-official-guide.65706/) but that didn't work.  --update: it's a Boot:1 error

After much trial and error, I was able to boot my system by pressing f12, selecting my ssd, then entering the boot flag "nv_disable=1 system".  I tried to run Multibeast hoping that would undo whatever your script did, but that didn't fix the problem.  I tried recovering from the backup I'd made with CCC, but that didn't work either.  I can still only boot using f12 followed by "nv_disable=1 system" and only one monitor comes on.  

And my front USB ports still don't work.

**Comment by n8binus** [comment]
I solved the problem by replacing the EFI folder on the system disk with the one on my backup volume.  [For details, see here.](https://www.tonymacx86.com/threads/boot0-gpt-test-test-done-boot1-error-solved.235212/) Since it took me four days to figure that out,  I wouldn't recommend al3xtjames's script for anyone as dumb with computers as I am.

**Comment by al3xtjames** [comment]
Hi,

Sorry for the troubles that you encountered when using my script. The only changes that my script makes are to the EFI partition, so reverting it to a backup should fix any issues. I should probably clarify this in the wiki.

**Comment by n8binus** [comment]
Yes, I suggest that instructions for cloning your repository with the recursive flag for those who already have a clover installation, as well as instructions for reverting all changes would be very helpful additions.
