### ISSUE TITLE
Sound problem with Z77X-ud5H after update 10.12.6

### ISSUE THREAD

**Issue by benevido** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#81]
## System Information

 - OS: macOS 10.12.6
 - Script: GA-Z77X macOS Install v2.1.0
 - MB: GA-Z77X-ud5h rev 1.1
 - CPU: Intel Core i5-3570K
 - IGPU: Intel HD Graphics 4000
 - dGPU:  NVIDIA GeForce GTX 960

## Issue Type

 - [ ] I'm trying to boot the macOS installer
 - [ ] I'm trying to boot my macOS install

 - [x] I'm encountering errors during/after the post-install script

 - [ ] Can you add support for my board?

## Issue Description

Hello,
I use your script to create an usb install of Sierra (no sound problem on 10.12.0) and  make an update of Sierra (10.12.6) and your script. I tried several AppleALC.kext found on the web but nothing works.
Thanks for your work and a possible solution to my issue.

**Comment by rukasz** [comment]
Strange but I have almost same config and for me it works. Maybe mb revision is the problem...

**Comment by benevido** [comment]
Yes it's possible. But I don't understand why it works perfectly on 10.12.0 and don't on 12.10.6 ...

**Comment by rukasz** [comment]
Maube You should try a fresh install...

**Comment by benevido** [comment]
Could you post your AppleHDA.kex, if you're on 10.12.6 obviously ?

**Comment by benevido** [comment]
I made a fresh install and it works. I think I broke my install when I do a clover update...
