### ISSUE TITLE
stopped working after 6 months

### ISSUE THREAD

**Issue by vitordino** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#88]
Hi Alex, i used your repo as a base to my install (GA-Z77X-D3H) and it worked pretty well for 6 months or a little more

## Issue Type
 - [ ] I'm trying to boot the macOS installer
 - [X] I'm trying to boot my macOS install

Now i've tried to turn it on, its stuck on `hid legacy shim 2`, white crossed (prohibited) sign.

I did put back my EFI backup and it didn't solve the issue, put back your vanilla files, and didn't solve it either.

Any ideas what should be going wrong? Are there more than the EFI partition i'm not remembering?

I don't have any graphic card and removed all unecessary things (wifi card etc)

**Comment by Gerard71** [comment]
hello did you have a system update between when it was working and when it was not working anymore?
you can try to boot using a usb key or an external hard drive

if it does not work you can erase everything, restore with a backup time machine if you have one, start the backup with the usb key and put your EFI folder in the EFI partition

**Comment by vitordino** [comment]
i did not update it.

but thanks, i will try the usb before another clean install (:

**Comment by vitordino** [comment]
I used the repo again and suceeded on booting it, only the audio didn't work.

So i accidentally messed with codecs outside the EFI partition and now it stopped booting again (kp on late bootscreen)
Can someone send me a `.zip` of `/Library/Extensions/` and `System/Library/Extensions/` to fix it again 🙃
