### ISSUE TITLE
USB issues

### ISSUE THREAD

**Issue by alxgarza** [theracermaster/Gigabyte-GA-Z77X-DSDT-Patch#9]
Testing with a GA-Z77X-UD5H.  Can't get usb ports to work right.  Some USB ports work fine, Some USB ports do not work at all and some work erratically.

**Comment by theracermaster** [comment]
Can you please elaborate? What version of OS X, and what ports specifically are not working? What devices do you have plugged in? Can you also post a dump from IORegistryExplorer?

**Comment by alxgarza** [comment]
Hi Alex,

  Thank you for responding so fast.

I just upgraded to el capitain.

Can’t get IORegistryExplorer to work. How else can I get a dump of the USB ports?


Alex

**Comment by theracermaster** [comment]
Try [IORegistryExplorer v2.1](https://github.com/toleda/audio_ALCInjection/blob/master/IORegistryExplorer_v2.1.zip).

**Comment by alxgarza** [comment]
Does not work. I get the spinning color wheel.  And application not responding.

any Ideas?

I also tried IOjones and IORegistryExplorer-SLRID_v10.6.3 with the same results.

**Comment by theracermaster** [comment]
Interesting, works fine here. You can try an alternative, [IOJones](http://sourceforge.net/projects/iojones/).

**Comment by alxgarza** [comment]
Same problem with IOJones.


It seems that only the usb 2 work fine.
The USB3 ports work as USB2 but erratically.
And some USB3 ports do not work at all.

**Comment by alxgarza** [comment]
Hi Alex,

  After 17 minutes of the spinning wheel, IORegistryExplorer finally opened.

But the saved file size is 36MB.  How can I share it with you?

**Comment by alxgarza** [comment]
https://www.dropbox.com/s/nr6p2nl410h1edc/Alex%E2%80%99s%20iMac.ioreg?dl=0 <https://www.dropbox.com/s/nr6p2nl410h1edc/Alex%E2%80%99s%20iMac.ioreg?dl=0>

**Comment by theracermaster** [comment]
SSDT doesn't seem to be applying properly for your hardware. Can you post your config.plist & EFI/Clover/ACPI/patched folder?

**Comment by alxgarza** [comment]
Hi Alex,

I just saw your mail.

Thanks for your help.

**Comment by alxgarza** [comment]
Hi Alex,

When compiling ssdt I get an error.

Had to do download and mv manually.

Regards,

Alex










agarza:Gigabyte-GA-Z77X-DSDT-Patch agarza$ ./GA-Z77X.sh --compile-ssdt

Gigabyte GA-Z77X.sh Post-Install Script v1.8.1 by theracermaster
Updates & Info: https://github.com/theracermaster/Gigabyte-GA-Z77X-DSDT-Patch
--------------------------------------------------------------------------------
Detected motherboard: Gigabyte GA-Z77X-UD5H
Script arguments: ./GA-Z77X.sh --install-ssdt: Compiling Custom SSDT
--------------------------------------------------------------------------------
Downloading SSDT-GA-Z77X-UD5H.dsl:
######################################################################## 100.0%
Compiling SSDT-GA-Z77X-UD5H.dsl:

Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20150818-64
Copyright (c) 2000 - 2015 Intel Corporation

ASL Input:     /tmp/SSDT-GA-Z77X-UD5H.dsl - 492 lines, 14693 bytes, 223 keywords
AML Output:    /tmp/SSDT-GA-Z77X-UD5H.aml - 3103 bytes, 107 named objects, 116 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 14 Optimizations
mv: /Volumes/Home/Desktop/el capitain usb/untitled folder/Gigabyte-GA-Z77X-DSDT-Patch/EFI/CLOVER/ACPI/patched/SSDT.aml: set owner/group (was: 501/0): Operation not permitted

**Comment by theracermaster** [comment]
Also, you'll want to try setting xHCI Mode to `Enabled` in the UEFI. I need more info about your setup to properly diagnose what's going wrong, please post your EFI/Clover folder.

**Comment by alxgarza** [comment]
Hi Alex,

  xHCi is set to enable.

I had trouble with your script since it was not detecting the correct EFI volume.  So I modified your script to chose the correct volume and now it seems the USB ports are working fine.  But lost sound.


Thanks for your help.

**Comment by theracermaster** [comment]
Post an IOReg if audio isn't working for you.

**Comment by Philipondio** [comment]
Hi all,
I actually have the same problem. What do you need from me or how can I please solve this issue?

**Comment by theracermaster** [comment]
Are you having USB issues or audio issues? Post an IOReg dump with [IORegistryExplorer v2.1](https://github.com/toleda/audio_ALCInjection/blob/master/IORegistryExplorer_v2.1.zip).

**Comment by alxgarza** [comment]
I fixed my audio problems by removing AppleHDA898.kext and installing toledas audio.
